### ISSUE TITLE
ClientInteriorLayoutManager.cpp

### ISSUE THREAD

**Issue by TalisaKnight** [SWG-Source/client-tools#15]
Not sure if this was discovered yet or not but, after running the recent client-tools commit in #github-activity, the following errors came out when compiling new client:

C2065 - 'ms_disableInteriorLayouts' : uncdeclared identifier - clientGame - clientinteriorlayoutmanager.cpp - line: 46
C2065 - 'ms_disableInteriorLayouts' : uncdeclared identifier - clientGame - clientinteriorlayoutmanager.cpp - line: 64
C2065 - 'ms_disableInteriorLayouts' : uncdeclared identifier - clientGame - clientinteriorlayoutmanager.cpp - line: 138

**Comment by Cekis** [comment]
Looks like somebody forgot to make changes to the header file.  @AconiteX

**Comment by AconiteX** [comment]
The variable is defined in the namespace, it doesn't need to be in the header file. Client builds fine. Please review however this was patched. 

![image](https://user-images.githubusercontent.com/63141077/135924042-bf583839-8b74-4882-8716-1525a7eb6ec2.png)

**Comment by Cekis** [comment]
Closing.
