### ISSUE TITLE
TCG menu button needs to be removed

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/client-tools#2]
In the main menu used in-game there is an obsolete button for launching the Trading Card Game (TCG). 

This should be removed.

**Comment by FatCatTuxedo** [comment]
https://github.com/SWG-Source/client-assets/pull/4

**Comment by AconiteX** [comment]
believe this was fixed via d9f5d361

**Comment by TalisaKnight** [comment]
Yeah, I can't remember who that was, but someone did the fix on their fork of the repo.

**Comment by AconiteX** [comment]
Fixed via 82c76fe859, 80ddaf207e, and SWG-Source/client-assets@d00d8a5aafc42b8b8ea6ecd4046efeab859d831e
