### ISSUE TITLE
Help button issue

### ISSUE THREAD

**Issue by IrishDarkshadow** [SWG-Source/client-tools#3]
The main-menu help button needs to be updated with current links or removed.

**Comment by FatCatTuxedo** [comment]
https://github.com/SWG-Source/client-assets/pull/4

**Comment by AconiteX** [comment]
Fixed via 82c76fe859, 80ddaf207e, and SWG-Source/client-assets@d00d8a5aafc42b8b8ea6ecd4046efeab859d831e
